FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Cloud Run injects PORT natively. Use shell command to evaluate it
ENV PORT=8080
CMD uvicorn app.main:app --host 0.0.0.0 --port ${PORT}
